<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
// use Database\Seeder\DB;
use Illuminate\Support\Facades\DB;

class TimezonesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $timezones = [
            ['country_code' => 'AF', 'country_name' => 'Afghanistan' ,'timezone' => 'Asia/Kabul', 'utc_offset' => 'UTC +04:30'],
            ['country_code' => 'AL', 'country_name' => 'Albania', 'timezone' => 'Europe/Tirane', 'utc_offset' => 'UTC +02:00'],
            ['country_code' => 'DZ', 'country_name' => 'Algeria', 'timezone' => 'Africa/Algiers', 'utc_offset' => 'UTC +01:00'],
            ['country_code' => 'AS', 'country_name' => 'American Samoa', 'timezone' => 'Pacific/Pago_Pago', 'utc_offset' => 'UTC -11:00'],
            ['country_code' => 'AD', 'country_name' => 'Andorra', 'timezone' => 'Europe/Andorra', 'utc_offset' => 'UTC +02:00'],
            ['country_code' => 'AO', 'country_name' => 'Angola', 'timezone' => 'Africa/Luanda', 'utc_offset' => 'UTC +01:00'],
            ['country_code' => 'AI', 'country_name' => 'Anguilla', 'timezone' => 'America/Anguilla', 'utc_offset' => 'UTC -04:00'],
            ['country_code' => 'AQ', 'country_name' => 'Antarctica', 'timezone' => 'Antarctica/Casey', 'utc_offset' => 'UTC +11:00'],
            ['country_code' => 'AQ', 'country_name' => 'Antarctica', 'timezone' => 'Antarctica/Davis', 'utc_offset' => 'UTC +07:00'],
            ['country_code' => 'AQ', 'country_name' => 'Antarctica', 'timezone' => 'Antarctica/DumontDUrville', 'utc_offset' => 'UTC +10:00'],
            ['country_code' => 'AQ', 'country_name' => 'Antarctica', 'timezone' => 'Antarctica/Mawson', 'utc_offset' => 'UTC +05:00'],
            ['country_code' => 'AQ', 'country_name' => 'Antarctica', 'timezone' => 'Antarctica/McMurdo', 'utc_offset' => 'UTC +12:00'],
            ['country_code' => 'AQ', 'country_name' => 'Antarctica', 'timezone' => 'Antarctica/Palmer', 'utc_offset' => 'UTC -03:00'],
            ['country_code' => 'AQ', 'country_name' => 'Antarctica', 'timezone' => 'Antarctica/Rothera', 'utc_offset' => 'UTC -03:00'],
            ['country_code' => 'AQ', 'country_name' => 'Antarctica', 'timezone' => 'Antarctica/Syowa', 'utc_offset' => 'UTC +03:00'],
            ['country_code' => 'AQ', 'country_name' => 'Antarctica', 'timezone' => 'Antarctica/Troll', 'utc_offset' => 'UTC +02:00'],
            ['country_code' => 'AQ', 'country_name' => 'Antarctica', 'timezone' => 'Antarctica/Vostok', 'utc_offset' => 'UTC +06:00'],
            ['country_code' => 'AG', 'country_name' => 'Antigua and Barbuda', 'timezone' => 'America/Antigua', 'utc_offset' => 'UTC -04:00'],
            ['country_code' => 'AR', 'country_name' => 'Argentina', 'timezone' => 'America/Argentina/Buenos_Aires', 'utc_offset' => 'UTC -03:00'],
            ['country_code' => 'AR', 'country_name' => 'Argentina', 'timezone' => 'America/Argentina/Catamarca', 'utc_offset' => 'UTC -03:00'],
            ['country_code' => 'AR', 'country_name' => 'Argentina', 'timezone' => 'America/Argentina/Cordoba', 'utc_offset' => 'UTC -03:00'],
            ['country_code' => 'AR', 'country_name' => 'Argentina', 'timezone' => 'America/Argentina/Jujuy', 'utc_offset' => 'UTC -03:00'],
            ['country_code' => 'AR', 'country_name' => 'Argentina', 'timezone' => 'America/Argentina/La_Rioja', 'utc_offset' => 'UTC -03:00'],
            ['country_code' => 'AR', 'country_name' => 'Argentina', 'timezone' => 'America/Argentina/Mendoza', 'utc_offset' => 'UTC -03:00'],
            ['country_code' => 'AR', 'country_name' => 'Argentina', 'timezone' => 'America/Argentina/Rio_Gallegos', 'utc_offset' => 'UTC -03:00'],
            ['country_code' => 'AR', 'country_name' => 'Argentina', 'timezone' => 'America/Argentina/Salta', 'utc_offset' => 'UTC -03:00'],
            ['country_code' => 'AR', 'country_name' => 'Argentina', 'timezone' => 'America/Argentina/San_Juan', 'utc_offset' => 'UTC -03:00'],
            ['country_code' => 'AR', 'country_name' => 'Argentina', 'timezone' => 'America/Argentina/San_Luis', 'utc_offset' => 'UTC -03:00'],
            ['country_code' => 'AR', 'country_name' => 'Argentina', 'timezone' => 'America/Argentina/Tucuman', 'utc_offset' => 'UTC -03:00'],
            ['country_code' => 'AR', 'country_name' => 'Argentina', 'timezone' => 'America/Argentina/Ushuaia', 'utc_offset' => 'UTC -03:00'],
            ['country_code' => 'AM', 'country_name' => 'Armenia', 'timezone' => 'Asia/Yerevan', 'utc_offset' => 'UTC +04:00'],
            ['country_code' => 'AW', 'country_name' => 'Aruba', 'timezone' => 'America/Aruba', 'utc_offset' => 'UTC -04:00'],
            ['country_code' => 'AU', 'country_name' => 'Australia', 'timezone' => 'Antarctica/Macquarie', 'utc_offset' => 'UTC +10:00'],
            ['country_code' => 'AU', 'country_name' => 'Australia', 'timezone' => 'Australia/Adelaide', 'utc_offset' => 'UTC +09:30'],
            ['country_code' => 'AU', 'country_name' => 'Australia', 'timezone' => 'Australia/Brisbane', 'utc_offset' => 'UTC +10:00'],
            ['country_code' => 'AU', 'country_name' => 'Australia', 'timezone' => 'Australia/Broken_Hill', 'utc_offset' => 'UTC +09:30'],
            ['country_code' => 'AU', 'country_name' => 'Australia', 'timezone' => 'Australia/Darwin', 'utc_offset' => 'UTC +09:30'],
            ['country_code' => 'AU', 'country_name' => 'Australia', 'timezone' => 'Australia/Eucla', 'utc_offset' => 'UTC +08:45'],
            ['country_code' => 'AU', 'country_name' => 'Australia', 'timezone' => 'Australia/Hobart', 'utc_offset' => 'UTC +10:00'],
            ['country_code' => 'AU', 'country_name' => 'Australia', 'timezone' => 'Australia/Lindeman', 'utc_offset' => 'UTC +10:00'],
            ['country_code' => 'AU', 'country_name' => 'Australia', 'timezone' => 'Australia/Lord_Howe', 'utc_offset' => 'UTC +10:30'],
            ['country_code' => 'AU', 'country_name' => 'Australia', 'timezone' => 'Australia/Melbourne', 'utc_offset' => 'UTC +10:00'],
            ['country_code' => 'AU', 'country_name' => 'Australia', 'timezone' => 'Australia/Perth', 'utc_offset' => 'UTC +08:00'],
            ['country_code' => 'AU', 'country_name' => 'Australia', 'timezone' => 'Australia/Sydney', 'utc_offset' => 'UTC +10:00'],
            ['country_code' => 'AT', 'country_name' => 'Austria', 'timezone' => 'Europe/Vienna', 'utc_offset' => 'UTC +02:00'],
            ['country_code' => 'AZ', 'country_name' => 'Azerbaijan', 'timezone' => 'Asia/Baku', 'utc_offset' => 'UTC +04:00'],
            ['country_code' => 'BS', 'country_name' => 'Bahamas', 'timezone' => 'America/Nassau', 'utc_offset' => 'UTC -04:00'],
            ['country_code' => 'BH', 'country_name' => 'Bahrain', 'timezone' => 'Asia/Bahrain', 'utc_offset' => 'UTC +03:00'],
            ['country_code' => 'BD', 'country_name' => 'Bangladesh', 'timezone' => 'Asia/Dhaka', 'utc_offset' => 'UTC +06:00'],
            ['country_code' => 'BB', 'country_name' => 'Barbados', 'timezone' => 'America/Barbados', 'utc_offset' => 'UTC -04:00'],
            ['country_code' => 'BY', 'country_name' => 'Belarus', 'timezone' => 'Europe/Minsk', 'utc_offset' => 'UTC +03:00'],
            ['country_code' => 'BE', 'country_name' => 'Belgium', 'timezone' => 'Europe/Brussels', 'utc_offset' => 'UTC +02:00'],
            ['country_code' => 'BZ', 'country_name' => 'Belize', 'timezone' => 'America/Belize', 'utc_offset' => 'UTC -06:00'],
            ['country_code' => 'BJ', 'country_name' => 'Benin', 'timezone' => 'Africa/Porto-Novo', 'utc_offset' => 'UTC +01:00'],
            ['country_code' => 'BM', 'country_name' => 'Bermuda', 'timezone' => 'Atlantic/Bermuda', 'utc_offset' => 'UTC -03:00'],
            ['country_code' => 'BT', 'country_name' => 'Bhutan', 'timezone' => 'Asia/Thimphu', 'utc_offset' => 'UTC +06:00'],
            ['country_code' => 'BO', 'country_name' => 'Bolivia (Plurinational State of)', 'timezone' => 'America/La_Paz', 'utc_offset' => 'UTC -04:00'],
            ['country_code' => 'BQ', 'country_name' => 'Bonaire, Sint Eustatius and Saba', 'timezone' => 'America/Kralendijk', 'utc_offset' => 'UTC -04:00'],
            ['country_code' => 'BA', 'country_name' => 'Bosnia and Herzegovina', 'timezone' => 'Europe/Sarajevo', 'utc_offset' => 'UTC +02:00'],
            ['country_code' => 'BW', 'country_name' => 'Botswana', 'timezone' => 'Africa/Gaborone', 'utc_offset' => 'UTC +02:00'],
            ['country_code' => 'BR', 'country_name' => 'Brazil', 'timezone' => 'America/Araguaina', 'utc_offset' => 'UTC -03:00'],
            ['country_code' => 'BR', 'country_name' => 'Brazil', 'timezone' => 'America/Bahia', 'utc_offset' => 'UTC -03:00'],
            ['country_code' => 'BR', 'country_name' => 'Brazil', 'timezone' => 'America/Belem', 'utc_offset' => 'UTC -03:00'],
            ['country_code' => 'BR', 'country_name' => 'Brazil', 'timezone' => 'America/Boa_Vista', 'utc_offset' => 'UTC -04:00'],
            ['country_code' => 'BR', 'country_name' => 'Brazil', 'timezone' => 'America/Campo_Grande', 'utc_offset' => 'UTC -04:00'],
            ['country_code' => 'BR', 'country_name' => 'Brazil', 'timezone' => 'America/Cuiaba', 'utc_offset' => 'UTC -04:00'],
            ['country_code' => 'BR', 'country_name' => 'Brazil', 'timezone' => 'America/Eirunepe', 'utc_offset' => 'UTC -05:00'],
            ['country_code' => 'BR', 'country_name' => 'Brazil', 'timezone' => 'America/Fortaleza', 'utc_offset' => 'UTC -03:00'],
            ['country_code' => 'BR', 'country_name' => 'Brazil', 'timezone' => 'America/Maceio', 'utc_offset' => 'UTC -03:00'],
            ['country_code' => 'BR', 'country_name' => 'Brazil', 'timezone' => 'America/Manaus', 'utc_offset' => 'UTC -04:00'],
            ['country_code' => 'BR', 'country_name' => 'Brazil', 'timezone' => 'America/Noronha', 'utc_offset' => 'UTC -02:00'],
            ['country_code' => 'BR', 'country_name' => 'Brazil', 'timezone' => 'America/Porto_Velho', 'utc_offset' => 'UTC -04:00'],
            ['country_code' => 'BR', 'country_name' => 'Brazil', 'timezone' => 'America/Recife', 'utc_offset' => 'UTC -03:00'],
            ['country_code' => 'BR', 'country_name' => 'Brazil', 'timezone' => 'America/Rio_Branco', 'utc_offset' => 'UTC -05:00'],
            ['country_code' => 'BR', 'country_name' => 'Brazil', 'timezone' => 'America/Santarem', 'utc_offset' => 'UTC -03:00'],
            ['country_code' => 'BR', 'country_name' => 'Brazil', 'timezone' => 'America/Sao_Paulo', 'utc_offset' => 'UTC -03:00'],
            ['country_code' => 'IO', 'country_name' => 'British Indian Ocean Territory', 'timezone' => 'Indian/Chagos', 'utc_offset' => 'UTC +06:00'],
            ['country_code' => 'BN', 'country_name' => 'Brunei Darussalam', 'timezone' => 'Asia/Brunei', 'utc_offset' => 'UTC +08:00'],
            ['country_code' => 'BG', 'country_name' => 'Bulgaria', 'timezone' => 'Europe/Sofia', 'utc_offset' => 'UTC +03:00'],
            ['country_code' => 'BF', 'country_name' => 'Burkina Faso', 'timezone' => 'Africa/Ouagadougou', 'utc_offset' => 'UTC +00:00'],
            ['country_code' => 'BI', 'country_name' => 'Burundi', 'timezone' => 'Africa/Bujumbura', 'utc_offset' => 'UTC +02:00'],
            ['country_code' => 'KH', 'country_name' => 'Cambodia', 'timezone' => 'Asia/Phnom_Penh', 'utc_offset' => 'UTC +07:00'],
            ['country_code' => 'CM', 'country_name' => 'Cameroon', 'timezone' => 'Africa/Douala', 'utc_offset' => 'UTC +01:00'],
            ['country_code' => 'CA', 'country_name' => 'Canada', 'timezone' => 'America/Atikokan', 'utc_offset' => 'UTC -05:00'],
            ['country_code' => 'CA', 'country_name' => 'Canada', 'timezone' => 'America/Blanc-Sablon', 'utc_offset' => 'UTC -04:00'],
            ['country_code' => 'CA', 'country_name' => 'Canada', 'timezone' => 'America/Cambridge_Bay', 'utc_offset' => 'UTC -06:00'],
            ['country_code' => 'CA', 'country_name' => 'Canada', 'timezone' => 'America/Creston', 'utc_offset' => 'UTC -07:00'],
            ['country_code' => 'CA', 'country_name' => 'Canada', 'timezone' => 'America/Dawson', 'utc_offset' => 'UTC -07:00'],
            ['country_code' => 'CA', 'country_name' => 'Canada', 'timezone' => 'America/Dawson_Creek', 'utc_offset' => 'UTC -07:00'],
            ['country_code' => 'CA', 'country_name' => 'Canada', 'timezone' => 'America/Edmonton', 'utc_offset' => 'UTC -06:00'],
            ['country_code' => 'CA', 'country_name' => 'Canada', 'timezone' => 'America/Fort_Nelson', 'utc_offset' => 'UTC -07:00'],
            ['country_code' => 'CA', 'country_name' => 'Canada', 'timezone' => 'America/Glace_Bay', 'utc_offset' => 'UTC -03:00'],
            ['country_code' => 'CA', 'country_name' => 'Canada', 'timezone' => 'America/Goose_Bay', 'utc_offset' => 'UTC -03:00'],
            ['country_code' => 'CA', 'country_name' => 'Canada', 'timezone' => 'America/Halifax', 'utc_offset' => 'UTC -03:00'],
            ['country_code' => 'CA', 'country_name' => 'Canada', 'timezone' => 'America/Inuvik', 'utc_offset' => 'UTC -06:00'],
            ['country_code' => 'CA', 'country_name' => 'Canada', 'timezone' => 'America/Iqaluit', 'utc_offset' => 'UTC -04:00'],
            ['country_code' => 'CA', 'country_name' => 'Canada', 'timezone' => 'America/Moncton', 'utc_offset' => 'UTC -03:00'],
            ['country_code' => 'CA', 'country_name' => 'Canada', 'timezone' => 'America/Rankin_Inlet', 'utc_offset' => 'UTC -05:00'],
            ['country_code' => 'CA', 'country_name' => 'Canada', 'timezone' => 'America/Regina', 'utc_offset' => 'UTC -06:00'],
            ['country_code' => 'CA', 'country_name' => 'Canada', 'timezone' => 'America/Resolute', 'utc_offset' => 'UTC -05:00'],
            ['country_code' => 'CA', 'country_name' => 'Canada', 'timezone' => 'America/St_Johns', 'utc_offset' => 'UTC -02:30'],
            ['country_code' => 'CA', 'country_name' => 'Canada', 'timezone' => 'America/Swift_Current', 'utc_offset' => 'UTC -06:00'],
            ['country_code' => 'CA', 'country_name' => 'Canada', 'timezone' => 'America/Toronto', 'utc_offset' => 'UTC -04:00'],
            ['country_code' => 'CA', 'country_name' => 'Canada', 'timezone' => 'America/Vancouver', 'utc_offset' => 'UTC -07:00'],
            ['country_code' => 'CA', 'country_name' => 'Canada', 'timezone' => 'America/Whitehorse', 'utc_offset' => 'UTC -07:00'],
            ['country_code' => 'CA', 'country_name' => 'Canada', 'timezone' => 'America/Winnipeg', 'utc_offset' => 'UTC -05:00'],
            ['country_code' => 'CV', 'country_name' => 'Cape Verde', 'timezone' => 'Atlantic/Cape_Verde', 'utc_offset' => 'UTC -01:00'],
            ['country_code' => 'KY', 'country_name' => 'Cayman Islands', 'timezone' => 'America/Cayman', 'utc_offset' => 'UTC -05:00'],
            ['country_code' => 'CF', 'country_name' => 'Central African Republic', 'timezone' => 'Africa/Bangui', 'utc_offset' => 'UTC +01:00'],
            ['country_code' => 'TD', 'country_name' => 'Chad', 'timezone' => 'Africa/Ndjamena', 'utc_offset' => 'UTC +01:00'],
            ['country_code' => 'CL', 'country_name' => 'Chile', 'timezone' => 'America/Punta_Arenas', 'utc_offset' => 'UTC -03:00'],
            ['country_code' => 'CL', 'country_name' => 'Chile', 'timezone' => 'America/Santiago', 'utc_offset' => 'UTC -04:00'],
            ['country_code' => 'CL', 'country_name' => 'Chile', 'timezone' => 'Pacific/Easter', 'utc_offset' => 'UTC -06:00'],
            ['country_code' => 'CN', 'country_name' => 'China', 'timezone' => 'Asia/Shanghai', 'utc_offset' => 'UTC +08:00'],
            ['country_code' => 'CN', 'country_name' => 'China', 'timezone' => 'Asia/Urumqi', 'utc_offset' => 'UTC +06:00'],
            ['country_code' => 'CX', 'country_name' => 'Christmas Island', 'timezone' => 'Indian/Christmas', 'utc_offset' => 'UTC +07:00'],
            ['country_code' => 'CC', 'country_name' => 'Cocos (Keeling) Islands', 'timezone' => 'Indian/Cocos', 'utc_offset' => 'UTC +06:30'],
            ['country_code' => 'CO', 'country_name' => 'Colombia', 'timezone' => 'America/Bogota', 'utc_offset' => 'UTC -05:00'],
            ['country_code' => 'KM', 'country_name' => 'Comoros', 'timezone' => 'Indian/Comoro', 'utc_offset' => 'UTC +03:00'],
            ['country_code' => 'CG', 'country_name' => 'Congo', 'timezone' => 'Africa/Brazzaville', 'utc_offset' => 'UTC +01:00'],
            ['country_code' => 'CD', 'country_name' => 'Congo, the Democratic Republic of the', 'timezone' => 'Africa/Kinshasa', 'utc_offset' => 'UTC +01:00'],
            ['country_code' => 'CD', 'country_name' => 'Congo, the Democratic Republic of the', 'timezone' => 'Africa/Lubumbashi', 'utc_offset' => 'UTC +02:00'],
            ['country_code' => 'CK', 'country_name' => 'Cook Islands', 'timezone' => 'Pacific/Rarotonga', 'utc_offset' => 'UTC -10:00'],
            ['country_code' => 'CR', 'country_name' => 'Costa Rica', 'timezone' => 'America/Costa_Rica', 'utc_offset' => 'UTC -06:00'],
            ['country_code' => 'HR', 'country_name' => 'Croatia', 'timezone' => 'Europe/Zagreb', 'utc_offset' => 'UTC +02:00'],
            ['country_code' => 'CU', 'country_name' => 'Cuba', 'timezone' => 'America/Havana', 'utc_offset' => 'UTC -04:00'],
            ['country_code' => 'CW', 'country_name' => 'Curaçao', 'timezone' => 'America/Curacao', 'utc_offset' => 'UTC -04:00'],
            ['country_code' => 'CY', 'country_name' => 'Cyprus', 'timezone' => 'Asia/Famagusta', 'utc_offset' => 'UTC +03:00'],
            ['country_code' => 'CY', 'country_name' => 'Cyprus', 'timezone' => 'Asia/Nicosia', 'utc_offset' => 'UTC +03:00'],
            ['country_code' => 'CZ', 'country_name' => 'Czech Republic', 'timezone' => 'Europe/Prague', 'utc_offset' => 'UTC +02:00'],
            ['country_code' => 'CI', 'country_name' => 'Côte dIvoire', 'timezone' => 'Africa/Abidjan', 'utc_offset' => 'UTC +00:00'],
            ['country_code' => 'DK', 'country_name' => 'Denmark', 'timezone' => 'Europe/Copenhagen', 'utc_offset' => 'UTC +02:00'],
            ['country_code' => 'DJ', 'country_name' => 'Djibouti', 'timezone' => 'Africa/Djibouti', 'utc_offset' => 'UTC +03:00'],
            ['country_code' => 'DM', 'country_name' => 'Dominica', 'timezone' => 'America/Dominica', 'utc_offset' => 'UTC -04:00'],
            ['country_code' => 'DO', 'country_name' => 'Dominican Republic', 'timezone' => 'America/Santo_Domingo', 'utc_offset' => 'UTC -04:00'],
            ['country_code' => 'EC', 'country_name' => 'Ecuador', 'timezone' => 'America/Guayaquil', 'utc_offset' => 'UTC -05:00'],
            ['country_code' => 'EC', 'country_name' => 'Ecuador', 'timezone' => 'Pacific/Galapagos', 'utc_offset' => 'UTC -06:00'],
            ['country_code' => 'EG', 'country_name' => 'Egypt', 'timezone' => 'Africa/Cairo', 'utc_offset' => 'UTC +03:00'],
            ['country_code' => 'SV', 'country_name' => 'El Salvador', 'timezone' => 'America/El_Salvador', 'utc_offset' => 'UTC -06:00'],
            ['country_code' => 'GQ', 'country_name' => 'Equatorial Guinea', 'timezone' => 'Africa/Malabo', 'utc_offset' => 'UTC +01:00'],
            ['country_code' => 'ER', 'country_name' => 'Eritrea', 'timezone' => 'Africa/Asmara', 'utc_offset' => 'UTC +03:00'],
            ['country_code' => 'EE', 'country_name' => 'Estonia', 'timezone' => 'Europe/Tallinn', 'utc_offset' => 'UTC +03:00'],
            ['country_code' => 'ET', 'country_name' => 'Ethiopia', 'timezone' => 'Africa/Addis_Ababa', 'utc_offset' => 'UTC +03:00'],
            ['country_code' => 'FK', 'country_name' => 'Falkland Islands (Malvinas)', 'timezone' => 'Atlantic/Stanley', 'utc_offset' => 'UTC -03:00'],
            ['country_code' => 'FO', 'country_name' => 'Faroe Islands', 'timezone' => 'Atlantic/Faroe', 'utc_offset' => 'UTC +01:00'],
            ['country_code' => 'FJ', 'country_name' => 'Fiji', 'timezone' => 'Pacific/Fiji', 'utc_offset' => 'UTC +12:00'],
            ['country_code' => 'FI', 'country_name' => 'Finland', 'timezone' => 'Europe/Helsinki', 'utc_offset' => 'UTC +03:00'],
            ['country_code' => 'FR', 'country_name' => 'France', 'timezone' => 'Europe/Paris', 'utc_offset' => 'UTC +02:00'],
            ['country_code' => 'GF', 'country_name' => 'French Guiana', 'timezone' => 'America/Cayenne', 'utc_offset' => 'UTC -03:00'],
            ['country_code' => 'PF', 'country_name' => 'French Polynesia', 'timezone' => 'Pacific/Gambier', 'utc_offset' => 'UTC -09:00'],
            ['country_code' => 'PF', 'country_name' => 'French Polynesia', 'timezone' => 'Pacific/Marquesas', 'utc_offset' => 'UTC -09:30'],
            ['country_code' => 'PF', 'country_name' => 'French Polynesia', 'timezone' => 'Pacific/Tahiti', 'utc_offset' => 'UTC -10:00'],
            ['country_code' => 'TF', 'country_name' => 'French Southern Territories', 'timezone' => 'Indian/Kerguelen', 'utc_offset' => 'UTC +05:00'],
            ['country_code' => 'GA', 'country_name' => 'Gabon', 'timezone' => 'Africa/Libreville', 'utc_offset' => 'UTC +01:00'],
            ['country_code' => 'GM', 'country_name' => 'Gambia', 'timezone' => 'Africa/Banjul', 'utc_offset' => 'UTC +00:00'],
            ['country_code' => 'GE', 'country_name' => 'Georgia', 'timezone' => 'Asia/Tbilisi', 'utc_offset' => 'UTC +04:00'],
            ['country_code' => 'DE', 'country_name' => 'Germany', 'timezone' => 'Europe/Berlin', 'utc_offset' => 'UTC +02:00'],
            ['country_code' => 'DE', 'country_name' => 'Germany', 'timezone' => 'Europe/Busingen', 'utc_offset' => 'UTC +02:00'],
            ['country_code' => 'GH', 'country_name' => 'Ghana', 'timezone' => 'Africa/Accra', 'utc_offset' => 'UTC +00:00'],
            ['country_code' => 'GI', 'country_name' => 'Gibraltar', 'timezone' => 'Europe/Gibraltar', 'utc_offset' => 'UTC +02:00'],
            ['country_code' => 'GR', 'country_name' => 'Greece', 'timezone' => 'Europe/Athens', 'utc_offset' => 'UTC +03:00'],
            ['country_code' => 'GL', 'country_name' => 'Greenland', 'timezone' => 'America/Danmarkshavn', 'utc_offset' => 'UTC +00:00'],
            ['country_code' => 'GL', 'country_name' => 'Greenland', 'timezone' => 'America/Nuuk', 'utc_offset' => 'UTC -02:00'],
            ['country_code' => 'GL', 'country_name' => 'Greenland', 'timezone' => 'America/Scoresbysund', 'utc_offset' => 'UTC +00:00'],
            ['country_code' => 'GL', 'country_name' => 'Greenland', 'timezone' => 'America/Thule', 'utc_offset' => 'UTC -03:00'],
            ['country_code' => 'GD', 'country_name' => 'Grenada', 'timezone' => 'America/Grenada', 'utc_offset' => 'UTC -04:00'],
            ['country_code' => 'GP', 'country_name' => 'Guadeloupe', 'timezone' => 'America/Guadeloupe', 'utc_offset' => 'UTC -04:00'],
            ['country_code' => 'GU', 'country_name' => 'Guam', 'timezone' => 'Pacific/Guam', 'utc_offset' => 'UTC +10:00'],
            ['country_code' => 'GT', 'country_name' => 'Guatemala', 'timezone' => 'America/Guatemala', 'utc_offset' => 'UTC -06:00'],
            ['country_code' => 'GG', 'country_name' => 'Guernsey', 'timezone' => 'Europe/Guernsey', 'utc_offset' => 'UTC +01:00'],
            ['country_code' => 'GN', 'country_name' => 'Guinea', 'timezone' => 'Africa/Conakry', 'utc_offset' => 'UTC +00:00'],
            ['country_code' => 'GW', 'country_name' => 'Guinea-Bissau', 'timezone' => 'Africa/Bissau', 'utc_offset' => 'UTC +00:00'],
            ['country_code' => 'GY', 'country_name' => 'Guyana', 'timezone' => 'America/Guyana', 'utc_offset' => 'UTC -04:00'],
            ['country_code' => 'HT', 'country_name' => 'Haiti', 'timezone' => 'America/Port-au-Prince', 'utc_offset' => 'UTC -04:00'],
            ['country_code' => 'VA', 'country_name' => 'Holy See (Vatican City State)', 'timezone' => 'Europe/Vatican', 'utc_offset' => 'UTC +02:00'],
            ['country_code' => 'HN', 'country_name' => 'Honduras', 'timezone' => 'America/Tegucigalpa', 'utc_offset' => 'UTC -06:00'],
            ['country_code' => 'HK', 'country_name' => 'Hong Kong', 'timezone' => 'Asia/Hong_Kong', 'utc_offset' => 'UTC +08:00'],
            ['country_code' => 'HU', 'country_name' => 'Hungary', 'timezone' => 'Europe/Budapest', 'utc_offset' => 'UTC +02:00'],
            ['country_code' => 'IS', 'country_name' => 'Iceland', 'timezone' => 'Atlantic/Reykjavik', 'utc_offset' => 'UTC +00:00'],
            ['country_code' => 'IN', 'country_name' => 'India', 'timezone' => 'Asia/Kolkata', 'utc_offset' => 'UTC +05:30'],
            ['country_code' => 'ID', 'country_name' => 'Indonesia', 'timezone' => 'Asia/Jakarta', 'utc_offset' => 'UTC +07:00'],
            ['country_code' => 'ID', 'country_name' => 'Indonesia', 'timezone' => 'Asia/Jayapura', 'utc_offset' => 'UTC +09:00'],
            ['country_code' => 'ID', 'country_name' => 'Indonesia', 'timezone' => 'Asia/Makassar', 'utc_offset' => 'UTC +08:00'],
            ['country_code' => 'ID', 'country_name' => 'Indonesia', 'timezone' => 'Asia/Pontianak', 'utc_offset' => 'UTC +07:00'],
            ['country_code' => 'IR', 'country_name' => 'Iran (Islamic Republic of)', 'timezone' => 'Asia/Tehran', 'utc_offset' => 'UTC +03:30'],
            ['country_code' => 'IQ', 'country_name' => 'Iraq', 'timezone' => 'Asia/Baghdad', 'utc_offset' => 'UTC +03:00'],
            ['country_code' => 'IE', 'country_name' => 'Ireland', 'timezone' => 'Europe/Dublin', 'utc_offset' => 'UTC +01:00'],
            ['country_code' => 'IM', 'country_name' => 'Isle of Man', 'timezone' => 'Europe/Isle_of_Man', 'utc_offset' => 'UTC +01:00'],
            ['country_code' => 'IL', 'country_name' => 'Israel', 'timezone' => 'Asia/Jerusalem', 'utc_offset' => 'UTC +03:00'],
            ['country_code' => 'IT', 'country_name' => 'Italy', 'timezone' => 'Europe/Rome', 'utc_offset' => 'UTC +02:00'],
            ['country_code' => 'JM', 'country_name' => 'Jamaica', 'timezone' => 'America/Jamaica', 'utc_offset' => 'UTC -05:00'],
            ['country_code' => 'JP', 'country_name' => 'Japan', 'timezone' => 'Asia/Tokyo', 'utc_offset' => 'UTC +09:00'],
            ['country_code' => 'JE', 'country_name' => 'Jersey', 'timezone' => 'Europe/Jersey', 'utc_offset' => 'UTC +01:00'],
            ['country_code' => 'JO', 'country_name' => 'Jordan', 'timezone' => 'Asia/Amman', 'utc_offset' => 'UTC +03:00'],
            ['country_code' => 'KZ', 'country_name' => 'Kazakhstan', 'timezone' => 'Asia/Almaty', 'utc_offset' => 'UTC +06:00'],
            ['country_code' => 'KZ', 'country_name' => 'Kazakhstan', 'timezone' => 'Asia/Aqtau', 'utc_offset' => 'UTC +05:00'],
            ['country_code' => 'KZ', 'country_name' => 'Kazakhstan', 'timezone' => 'Asia/Aqtobe', 'utc_offset' => 'UTC +05:00'],
            ['country_code' => 'KZ', 'country_name' => 'Kazakhstan', 'timezone' => 'Asia/Atyrau', 'utc_offset' => 'UTC +05:00'],
            ['country_code' => 'KZ', 'country_name' => 'Kazakhstan', 'timezone' => 'Asia/Oral', 'utc_offset' => 'UTC +05:00'],
            ['country_code' => 'KZ', 'country_name' => 'Kazakhstan', 'timezone' => 'Asia/Qostanay', 'utc_offset' => 'UTC +06:00'],
            ['country_code' => 'KZ', 'country_name' => 'Kazakhstan', 'timezone' => 'Asia/Qyzylorda', 'utc_offset' => 'UTC +05:00'],
            ['country_code' => 'KE', 'country_name' => 'Kenya', 'timezone' => 'Africa/Nairobi', 'utc_offset' => 'UTC +03:00'],
            ['country_code' => 'KI', 'country_name' => 'Kiribati', 'timezone' => 'Pacific/Kanton', 'utc_offset' => 'UTC +13:00'],
            ['country_code' => 'KI', 'country_name' => 'Kiribati', 'timezone' => 'Pacific/Kiritimati', 'utc_offset' => 'UTC +14:00'],
            ['country_code' => 'KI', 'country_name' => 'Kiribati', 'timezone' => 'Pacific/Tarawa', 'utc_offset' => 'UTC +12:00'],
            ['country_code' => 'KP', 'country_name' => 'Korea (Democratic Peoples Republic of Korea)', 'timezone' => 'Asia/Pyongyang', 'utc_offset' => 'UTC +09:00'],
            ['country_code' => 'KR', 'country_name' => 'Korea (Republic of Korea)', 'timezone' => 'Asia/Seoul', 'utc_offset' => 'UTC +09:00'],
            ['country_code' => 'KW', 'country_name' => 'Kuwait', 'timezone' => 'Asia/Kuwait', 'utc_offset' => 'UTC +03:00'],
            ['country_code' => 'KG', 'country_name' => 'Kyrgyzstan', 'timezone' => 'Asia/Bishkek', 'utc_offset' => 'UTC +06:00'],
            ['country_code' => 'LA', 'country_name' => 'Lao Peoples Democratic Republic', 'timezone' => 'Asia/Vientiane', 'utc_offset' => 'UTC +07:00'],
            ['country_code' => 'LV', 'country_name' => 'Latvia', 'timezone' => 'Europe/Riga', 'utc_offset' => 'UTC +03:00'],
            ['country_code' => 'LB', 'country_name' => 'Lebanon', 'timezone' => 'Asia/Beirut', 'utc_offset' => 'UTC +03:00'],
            ['country_code' => 'LS', 'country_name' => 'Lesotho', 'timezone' => 'Africa/Maseru', 'utc_offset' => 'UTC +02:00'],
            ['country_code' => 'LR', 'country_name' => 'Liberia', 'timezone' => 'Africa/Monrovia', 'utc_offset' => 'UTC +00:00'],
            ['country_code' => 'LY', 'country_name' => 'Libya', 'timezone' => 'Africa/Tripoli', 'utc_offset' => 'UTC +02:00'],
            ['country_code' => 'LI', 'country_name' => 'Liechtenstein', 'timezone' => 'Europe/Vaduz', 'utc_offset' => 'UTC +02:00'],
            ['country_code' => 'LT', 'country_name' => 'Lithuania', 'timezone' => 'Europe/Vilnius', 'utc_offset' => 'UTC +03:00'],
            ['country_code' => 'LU', 'country_name' => 'Luxembourg', 'timezone' => 'Europe/Luxembourg', 'utc_offset' => 'UTC +02:00'],
            ['country_code' => 'MO', 'country_name' => 'Macao', 'timezone' => 'Asia/Macau', 'utc_offset' => 'UTC +08:00'],
            ['country_code' => 'MK', 'country_name' => 'Macedonia (the Former Yugoslav Republic of)', 'timezone' => 'Europe/Skopje', 'utc_offset' => 'UTC +01:00'],
            ['country_code' => 'MG', 'country_name' => 'Madagascar', 'timezone' => 'Indian/Antananarivo', 'utc_offset' => 'UTC +03:00'],
            ['country_code' => 'MW', 'country_name' => 'Malawi', 'timezone' => 'Africa/Blantyre', 'utc_offset' => 'UTC +02:00'],
            ['country_code' => 'MY', 'country_name' => 'Malaysia', 'timezone' => 'Asia/Kuala_Lumpur', 'utc_offset' => 'UTC +08:00'],
            ['country_code' => 'MY', 'country_name' => 'Malaysia', 'timezone' => 'Asia/Kuching', 'utc_offset' => 'UTC +08:00'],
            ['country_code' => 'MV', 'country_name' => 'Maldives', 'timezone' => 'Indian/Maldives', 'utc_offset' => 'UTC +05:00'],
            ['country_code' => 'ML', 'country_name' => 'Mali', 'timezone' => 'Africa/Bamako', 'utc_offset' => 'UTC +00:00'],
            ['country_code' => 'MT', 'country_name' => 'Malta', 'timezone' => 'Europe/Malta', 'utc_offset' => 'UTC +02:00'],
            ['country_code' => 'MH', 'country_name' => 'Marshall Islands', 'timezone' => 'Pacific/Kwajalein', 'utc_offset' => 'UTC +12:00'],
            ['country_code' => 'MH', 'country_name' => 'Marshall Islands', 'timezone' => 'Pacific/Majuro', 'utc_offset' => 'UTC +12:00'],
            ['country_code' => 'MQ', 'country_name' => 'Martinique', 'timezone' => 'America/Martinique', 'utc_offset' => 'UTC -04:00'],
            ['country_code' => 'MR', 'country_name' => 'Mauritania', 'timezone' => 'Africa/Nouakchott', 'utc_offset' => 'UTC +00:00'],
            ['country_code' => 'MU', 'country_name' => 'Mauritius', 'timezone' => 'Indian/Mauritius', 'utc_offset' => 'UTC +04:00'],
            ['country_code' => 'YT', 'country_name' => 'Mayotte', 'timezone' => 'Indian/Mayotte', 'utc_offset' => 'UTC +03:00'],
            ['country_code' => 'MX', 'country_name' => 'Mexico', 'timezone' => 'America/Bahia_Banderas', 'utc_offset' => 'UTC -06:00'],
            ['country_code' => 'MX', 'country_name' => 'Mexico', 'timezone' => 'America/Cancun', 'utc_offset' => 'UTC -05:00'],
            ['country_code' => 'MX', 'country_name' => 'Mexico', 'timezone' => 'America/Chihuahua', 'utc_offset' => 'UTC -06:00'],
            ['country_code' => 'MX', 'country_name' => 'Mexico', 'timezone' => 'America/Ciudad_Juarez', 'utc_offset' => 'UTC -06:00'],
            ['country_code' => 'MX', 'country_name' => 'Mexico', 'timezone' => 'America/Hermosillo', 'utc_offset' => 'UTC -07:00'],
            ['country_code' => 'MX', 'country_name' => 'Mexico', 'timezone' => 'America/Matamoros', 'utc_offset' => 'UTC -05:00'],
            ['country_code' => 'MX', 'country_name' => 'Mexico', 'timezone' => 'America/Mazatlan', 'utc_offset' => 'UTC -07:00'],
            ['country_code' => 'MX', 'country_name' => 'Mexico', 'timezone' => 'America/Merida', 'utc_offset' => 'UTC -06:00'],
            ['country_code' => 'MX', 'country_name' => 'Mexico', 'timezone' => 'America/Mexico_City', 'utc_offset' => 'UTC -06:00'],
            ['country_code' => 'MX', 'country_name' => 'Mexico', 'timezone' => 'America/Monterrey', 'utc_offset' => 'UTC -06:00'],
            ['country_code' => 'MX', 'country_name' => 'Mexico', 'timezone' => 'America/Ojinaga', 'utc_offset' => 'UTC -05:00'],
            ['country_code' => 'MX', 'country_name' => 'Mexico', 'timezone' => 'America/Tijuana', 'utc_offset' => 'UTC -07:00'],
            ['country_code' => 'FM', 'country_name' => 'Micronesia (Federated States of)', 'timezone' => 'Pacific/Chuuk', 'utc_offset' => 'UTC +10:00'],
            ['country_code' => 'FM', 'country_name' => 'Micronesia (Federated States of)', 'timezone' => 'Pacific/Kosrae', 'utc_offset' => 'UTC +11:00'],
            ['country_code' => 'FM', 'country_name' => 'Micronesia (Federated States of)', 'timezone' => 'Pacific/Pohnpei', 'utc_offset' => 'UTC +11:00'],
            ['country_code' => 'MD', 'country_name' => 'Moldova (Republic of)', 'timezone' => 'Europe/Chisinau', 'utc_offset' => 'UTC +02:00'],
            ['country_code' => 'MC', 'country_name' => 'Monaco', 'timezone' => 'Europe/Monaco', 'utc_offset' => 'UTC +01:00'],
        ];

        DB::table('timezones')->insert($timezones);
    }
}
