pipeline {
    agent any
    environment {
        REMOTE_HOST = credentials('EVERYTHING_ELSE_SERVER')
        REMOTE_USER = credentials('JENKINS_USER')
        REMOTE_PASSWORD = credentials('JENKINS_PASSWORD')
        REMOTE_DESTINATION = credentials('DAYSUPPORT_FE_REMOTE_PATH')
    }

    stages {
        stage('Checkout') {
            steps {
                // Checkout source code from repository
                checkout scm
            }
        }
        stage('Deploy to Production') {
            when {
                expression { currentBuild.resultIsBetterOrEqualTo('SUCCESS') }
            }
            steps {
                script {
                    // Use SSH key or password for authentication
                    sh "sshpass -p ${REMOTE_PASSWORD} scp -r ${WORKSPACE}/* ${REMOTE_USER}@${REMOTE_HOST}:${REMOTE_DESTINATION}"
                }
            }
        }
    }
}
